export const cumple = {
  enero: [
    { day: 1, name: "Solmarina Arrieta de Vergara" },
    { day: 2, name: "Elsa Roa de Cárdenas" },
    { day: 12, name: "Hernán Solano Duarte" },
    { day: 14, name: "Nestor Vargas Pérez" },
    { day: 19, name: "Jairo Martínez Pinzón" },
    { day: 24, name: "Solangel Meza Nuñez" },
    { day: 28, name: "Evelio Uribe Anaya" },
    { day: 30, name: "Luz Evelia Galvis Rueda" },
  ],
  febrero: [
    { day: 1, name: "Edgar Mantilla Maldonado" },
    { day: 4, name: "María Isabel Calderón Cárdenas" },
    { day: 12, name: "María del Pilar Acevedo Vargas" },
    { day: 12, name: "Martha Berdugo Gómez" },
    { day: 17, name: "Sergio Forero Becerra" },
    { day: 18, name: "Nubia Domínguez Vargas" },
    { day: 18, name: "Yasley Rocio Leal" },
    { day: 18, name: "Flor Tirado Moreno" },
    { day: 22, name: "Rafael Moreno" },
    { day: 26, name: "Luz Dary Ramos Jiménez" },
  ],
  marzo: [
    { day: 6, name: "ROSA RAMIREZ BERNAL" },
    { day: 7, name: "RICARDO PINZON MARTINEZ" },
    { day: 8, name: "ANITA RAMIREZ ESPARZA" },
    { day: 16, name: "MONICA GWINNER PEÑA" },
    { day: 18, name: "HUBER GUEVARA ASCANIO" },
    { day: 22, name: "NEPO GUEVARA ROJAS" },
    { day: 22, name: "ROSA LEONOR GAST GALAN" },
    { day: 26, name: "DELIA MORENO MORENO" },
    { day: 30, name: "ORLANDO FORERO PEREZ" },
    { day: 30, name: "CESAR FORERO PEREZ" },
  ],
  abril: [
    { day: 3, name: "LEONILDE LARROTA PORTILLA" },
    { day: 5, name: "ERIBERTO MALDONADO SILVA" },
    { day: 5, name: "JAIDER MEDINA MEDINA" },
    { day: 8, name: "YONIS E. CALDERON CASTRELLON" },
    { day: 10, name: "LUZ STELLA CAMACHO DE OVIEDO" },
    { day: 12, name: "ROSALBA QUIJANO PLATA" },
    { day: 13, name: "EDUARDO RODRIGUEZ MUÑOZ" },
    { day: 18, name: "SANDRA CARDENAS" },
    { day: 20, name: "ALVARO AGUDELO SANDOVAL" },
    { day: 22, name: "ZAIRA B. AVENDAÑO CARDENAS" },
    { day: 23, name: "LUIS GERARDO RAMIREZ MARTINEZ" },
    { day: 28, name: "CAMPO ELIAS MIRANDA ALVARADO" },
    { day: 30, name: "DIDIER CARRASCAL VASQUEZ" },
  ],
  mayo: [
    { day: 1, name: "CARLOS MARIO YAÑEZ ALBARRACIN" },
    { day: 10, name: "JOSE ROSARIO ARIZA FLOREZ" },
    { day: 13, name: "PEDRO URIBE GARCIA" },
    { day: 15, name: "FERNANDO ARDILA SERRANO" },
    { day: 19, name: "JUAN PABLO RIVERA" },
    { day: 19, name: "JOSE DEL CARMEN SANCHEZ APARICIO" },
    { day: 22, name: "ALFREDO COTE ROJAS" },
    { day: 25, name: "LUZ MARINA MATAJIRA ORTIZ" },
    { day: 25, name: "HECTOR ZAMBRANO GUALDRON" },
    { day: 26, name: "GLORIA BAUTISTA TOBO" },
  ],
  junio: [
    { day: 1, name: "MARTHA GONZALEZ PRADA" },
    { day: 2, name: "MARIA NANCY ARISMENDI CAICEDO" },
    { day: 5, name: "HELBERT OLARTE ORTEGA" },
    { day: 6, name: "CLAUDIA P. GARCIA BOHORQUEZ" },
    { day: 14, name: "BETXY SANCHEZ BAROBOSA" },
    { day: 17, name: "HUGO A. GUARIN GALVIS" },
    { day: 17, name: "VICTOR SANTOS RODRIGUEZ" },
    { day: 19, name: "INES VANEGAS GALAN" },
    { day: 19, name: "DAVID BECERRA NARIÑO" },
    { day: 20, name: "CECILIA GONZALEZ PRADA" },
    { day: 26, name: "MIGUEL LIZARAZO VILLAREAL" },
    { day: 28, name: "LAURA P. CONTRERAS FERNANDEZ" },
    { day: 28, name: "HERNAN NAVARRO GUARIN" },
  ],
  julio: [
    { day: 2, name: "CECILIA GONZALEZ PRADA" },
    { day: 8, name: "SONIA FORERO GARZON" },
    { day: 10, name: "VICTOR OCHICA MUÑOZ" },
    { day: 11, name: "ORLANDO LOPEZ BONILLA" },
    { day: 13, name: "MIREYA LUCIA JEREZ MEDINA" },
    { day: 16, name: "TERESA DELGADO ARBELAEZ" },
    { day: 19, name: "LUIS DANIEL SANCHEZ QUINTERO" },
    { day: 23, name: "RAFAEL BALLESTEROS TOLOZA" },
    { day: 23, name: "MYRIAM QUIÑONEZ DE PINTO" },
    { day: 24, name: "ISMAEL E. MENDOZA CHAPARRO" },
    { day: 25, name: "JAIME PINZON MENDEZ" },
    { day: 27, name: "JHON JAIRO MANTILLA" },
    { day: 31, name: "JORGE CUERVO BERRIO" },
  ],
  agosto: [
    { day: 5, name: "GLORIA CARVAJAL MORENO" },
    { day: 7, name: "GUSTAVO VERGARA BOHORQUEZ" },
    { day: 8, name: "ALBERTO CAMARGO MARTINEZ" },
    { day: 13, name: "ROSANA TINOCO PORTO" },
    { day: 13, name: "JESUS CASTRO ARNACHE" },
    { day: 18, name: "SAMUEL GUARGUATI RODRIGUEZ" },
    { day: 23, name: "ROSA E. REYES CASTRO" },
    { day: 23, name: "JAIME DELGADO RAMIREZ" },
    { day: 25, name: "MARIA PICO" },
    { day: 27, name: "SERAFIN MARTINEZ REYES" },
    { day: 28, name: "JESUS HOMERO CRUZ CELIS" },
    { day: 29, name: "DOMINGO GARCIA CANDELA" },
    { day: 30, name: "ADRIANA RAMOS JIMENEZ" },
  ],
  septiembre: [
    { day: 3, name: "GUSTAVO MENDIETA CHACON" },
    { day: 9, name: "ANA ELDA SANTAMARIA DIAZ" },
    { day: 14, name: "BRANLEY VEGA BERNAL" },
    { day: 20, name: "RICARDO RODRIGUEZ GOMEZ" },
    { day: 21, name: "DIEGO F. VALDIVIESO VILLAMIZAR" },
    { day: 26, name: "LUIS DANIEL REYES SOSA" },
    { day: 28, name: "MARIELA RAMIREZ RUEDA" },
    { day: 30, name: "CARLOS A. TOVAR NIÑO" },
  ],
  octubre: [
    { day: 5, name: "BERNARDA LEON MARTINEZ" },
    { day: 6, name: "ALICIA ALMEYDA" },
    { day: 6, name: "JOHAN DAVID PATIÑO VEGA" },
    { day: 9, name: "MARIA GLADYS BENITEZ ARANDA" },
    { day: 9, name: "ALVARO SANCHEZ MARTINEZ" },
    { day: 14, name: "MARIA JULIANA GOMEZ MORA" },
    { day: 14, name: "EDWARD L. GUEVARA BURGOS" },
    { day: 17, name: "JULIO TORRES LENGERKE" },
    { day: 22, name: "PEDRO LEON PEÑA RODRIGUEZ" },
    { day: 22, name: "MARTIN LEAL LEAL" },
    { day: 24, name: "LAUREANO LEON ASCENCIO" },
    { day: 25, name: "ANA ADELINA BUENAHORA ARDILA" },
  ],
  noviembre: [
    { day: 8, name: "CESAR HERNANDEZ ARIAS" },
    { day: 14, name: "MARLEN BECERRA LEON" },
    { day: 15, name: "CARLOS A. HERNANDEZ MORA" },
    { day: 16, name: "JORGE E. REYES ALVAREZ" },
    { day: 19, name: "JAIME SANCHEZ ALBA" },
    { day: 21, name: "EDGARDO GUTIERREZ GORDON" },
    { day: 22, name: "ISABEL C. MONTAÑA BECERRA" },
    { day: 24, name: "GLORIA GOMEZ BAYONA" },
    { day: 29, name: "JUAN CARLOS ALMEYDA GONZALEZ" },
    { day: 30, name: "ANA LILIANA RONDON TARAZONA" },
    { day: 30, name: "HERMES ARCINIEGAS ORTIZ" },
  ],
  diciembre: [
    { day: 1, name: "EDWIN SOTO URIBE" },
    { day: 2, name: "HECTOR CAMARGO GOMEZ" },
    { day: 5, name: "RAQUEL P. NAVAS MORA" },
    { day: 9, name: "JHONY COLON GARCÍA" },
    { day: 10, name: "NELLY GONZALEZ GELVEZ" },
    { day: 10, name: "DIEGO CORREA CEDEÑO" },
    { day: 21, name: "LUIS GILBERTO MORANTES BECERRA" },
    { day: 22, name: "SERGIO LOBO DELGADO" },
    { day: 23, name: "ALVARO AYALA MARTINEZ" },
    { day: 24, name: "LUZ STELLA ARIAS AMAYA" },
    { day: 28, name: "LINDELIA OCHOA LEYVA" },
    { day: 29, name: "JAIRO ARENAS ESTEVEZ" },
    { day: 30, name: "LIZARDO MENESES MONTERO" },
  ],
};